allowLocalFiles: true
inputDir: 'Advanced/lessons/slides'
output: '_site/slides/advanced'
pdf: true
pptx: true
images: png
options:
  looseYAML: false
  notes: true
  markdown:
    breaks: false
  pdfOutlines: true
  pdfNotes: true
