allowLocalFiles: true
options:
  inputDir: './lessons',
  output: './site/slides',
  looseYAML: false
  notes: true
  markdown:
    breaks: false
  pdf: true
  pptx: true
  pdfOutlines: true
  pdfNotes: true
  images: png
