allowLocalFiles: true
inputDir: 'Basics/lessons/slides'
output: '_site/slides'
pdf: true
pptx: true
images: png
options:
  looseYAML: false
  notes: true
  markdown:
    breaks: false
  pdfOutlines: true
  pdfNotes: true
